//
//  BusinessRules.swift
//  SenseFlow
//
//  Created on 2026-02-05.
//  业务规则和阈值常量
//

import Foundation

/// 业务规则 - 核心业务逻辑的配置值
enum BusinessRules {
    /// Smart 推荐相关
    enum SmartRecommendation {
        static let highConfidenceThreshold: Double = 0.7
        static let mediumConfidenceThreshold: Double = 0.5
        static let percentageMultiplier = 100
    }

    /// 剪贴板历史
    enum ClipboardHistory {
        static let defaultLimit = 200
        static let minLimit = 50
        static let maxLimit = 500
        static let limitStep = 50
    }

    /// 文件存储
    enum FileStorage {
        static let largeFileThreshold = 512 * 1024  // 512KB
    }

    /// 权限检查
    enum Permissions {
        static let checkInterval: Double = 0.5  // 秒
        static let recheckDelayShort: Double = 0.5
        static let recheckDelayLong: Double = 2.0
    }

    /// 加密
    enum Encryption {
        static let defaultJPEGQuality: CGFloat = 0.5
    }

    /// 时间间隔
    enum TimeInterval {
        static let successMessageDisplay: Double = 2.0  // 秒
    }

    /// 动画
    enum Animation {
        static let successFeedbackDuration: Double = 0.3  // 秒
        static let successDisplayDuration: UInt64 = 3_000_000_000  // 纳秒 (3秒)
        static let overlayVisibleDuration: UInt64 = 900_000_000
        static let overlayPostSessionHoldDuration: UInt64 = 200_000_000
    }

    /// 快捷键
    enum HotKey {
        /// 修饰键键码（录制时应忽略的单独修饰键）
        static let modifierKeyCodes: Set<UInt16> = [
            0x37,  // leftCommand
            0x38,  // leftShift
            0x3A,  // leftOption
            0x3B,  // leftControl
            0x3C,  // rightShift
            0x3D,  // rightOption
            0x3E   // rightControl
        ]
    }

    /// Langfuse 配置
    enum Langfuse {
        static let defaultSyncInterval: Double = 300.0  // 秒 (5分钟)
        static let defaultActiveLabel = "production"
        static let defaultStatus = "未同步"

        static let minSyncInterval: Double = 60.0   // 1分钟
        static let maxSyncInterval: Double = 3600.0 // 60分钟
        static let syncIntervalStep: Double = 60.0  // 1分钟步进
        static let secondsPerMinute: Double = 60.0

        static let oneMinute: Double = 60.0
        static let oneHour: Double = 3600.0
        static let oneDay: Double = 86400.0
        static let twoSeconds: UInt64 = 2_000_000_000
        static let threeSeconds: UInt64 = 3_000_000_000

        static let promptCacheTTL: Foundation.TimeInterval = 60.0  // 1分钟
        static let serviceCacheTTL: Foundation.TimeInterval = 300.0  // 5分钟
        static let defaultPromptLimit = 100
        static let defaultPageLimit = 50

        static let syncing = "同步中..."
        static let success = "同步成功"
        static func failure(_ error: String) -> String { "同步失败: \(error)" }
        static let justNow = "刚刚"
        static func minutesAgo(_ minutes: Int) -> String { "\(minutes) 分钟前" }
        static func hoursAgo(_ hours: Int) -> String { "\(hours) 小时前" }
        static func daysAgo(_ days: Int) -> String { "\(days) 天前" }
    }

    /// HTTP 状态码
    enum HTTPStatus {
        static let ok = 200
        static let clientErrorThreshold = 400
    }

    /// 性能和延迟
    enum Performance {
        static let textSelectionDebounce: Foundation.TimeInterval = 0.1  // 100ms
        static let maxRetryAttempts = 20
    }

    /// 数据转换
    enum DataConversion {
        static let bytesPerKilobyte: Double = 1024.0
    }

    /// 剪贴板监听
    enum ClipboardMonitor {
        static let pollingInterval: Foundation.TimeInterval = 0.5  // 秒
        static let defaultPauseDuration: Foundation.TimeInterval = 0.5  // 秒
        static let unknownAppName = "Unknown"

        enum SensitiveTypes {
            static let transient = "org.nspasteboard.TransientType"
            static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
            static let concealed = "org.nspasteboard.ConcealedType"
        }

        enum ImageTypes {
            static let jpeg = "public.jpeg"
            static let heic = "public.heic"
        }
    }

    /// 剪贴板项目
    enum ClipboardItem {
        static let ocrPreviewLength = 50
        static let oneMinute: Double = 60.0
        static let oneHour: Double = 3600.0
        static let oneDay: Double = 86400.0
    }

    /// 文本预览长度
    enum TextPreview {
        static let cardPreview = 50      // 卡片显示预览长度
        static let logPreview = 30       // 日志输出预览长度
        static let contextPreview = 100  // 上下文预览长度
    }
}
