//
//  ClipboardFilterManager.swift
//  SenseFlow
//
//  Created on 2026-02-06 for v0.5.0
//  统一的剪贴板过滤管理器
//

import Foundation
import AppKit

/// 过滤结果
struct FilterResult {
    let shouldFilter: Bool
    let reason: FilterReason?
}

/// 过滤原因
enum FilterReason {
    case sensitiveData
    case blacklistedApp
}

/// 剪贴板过滤管理器（单例）
class ClipboardFilterManager {

    // MARK: - Singleton

    static let shared = ClipboardFilterManager()

    // MARK: - Properties

    // 敏感数据类型（系统自动标记）
    private let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType(BusinessRules.ClipboardMonitor.SensitiveTypes.transient),
        NSPasteboard.PasteboardType(BusinessRules.ClipboardMonitor.SensitiveTypes.autoGenerated),
        NSPasteboard.PasteboardType(BusinessRules.ClipboardMonitor.SensitiveTypes.concealed)
    ]

    // MARK: - Initialization

    private init() {}

    // MARK: - Public Methods

    /// 判断是否应该过滤
    /// - Parameters:
    ///   - pasteboardTypes: 剪贴板数据类型（可选）
    ///   - appBundleID: 应用 Bundle ID（可选）
    ///   - appName: 应用名称（可选）
    /// - Returns: 过滤结果
    func shouldFilter(
        pasteboardTypes: [NSPasteboard.PasteboardType]?,
        appBundleID: String?,
        appName: String?
    ) -> FilterResult {
        // 优先级 1: 敏感数据类型
        if containsSensitiveData(pasteboardTypes) {
            return FilterResult(shouldFilter: true, reason: .sensitiveData)
        }

        // 优先级 2: 用户黑名单
        if isInUserBlacklist(appBundleID, appName) {
            return FilterResult(shouldFilter: true, reason: .blacklistedApp)
        }

        // 通过所有过滤规则
        return FilterResult(shouldFilter: false, reason: nil)
    }

    // MARK: - Private Methods

    /// 检查是否包含敏感数据类型
    private func containsSensitiveData(_ types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types = types else { return false }

        for sensitiveType in sensitiveTypes {
            if types.contains(sensitiveType) {
                return true
            }
        }
        return false
    }

    /// 检查是否在用户黑名单中
    private func isInUserBlacklist(_ bundleID: String?, _ appName: String?) -> Bool {
        let blacklist = getUserBlacklist()
        guard !blacklist.isEmpty else { return false }

        // 检查 Bundle ID（精确匹配）
        if let bundleID = bundleID, blacklist.contains(bundleID) {
            return true
        }

        // 检查应用名称（不区分大小写）
        if let appName = appName {
            let lowercasedAppName = appName.lowercased()
            for item in blacklist {
                if item.lowercased() == lowercasedAppName {
                    return true
                }
            }
        }

        return false
    }

    /// 获取用户黑名单
    private func getUserBlacklist() -> [String] {
        guard let listString = UserDefaults.standard.string(forKey: UserDefaultsKeys.filterAppList) else {
            return []
        }

        // 按换行符分割，去除空行和空格
        return listString
            .components(separatedBy: CharacterSet.newlines)
            .map { $0.trimmingCharacters(in: CharacterSet.whitespaces) }
            .filter { !$0.isEmpty }
    }
}
